[aw-qt]
# Remove aw-server from autostart since it's running in Docker, and uncomment the line below.
autostart_modules = ["aw-watcher-afk", "aw-watcher-window"]

[aw-qt-testing]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window"]
